name: quark
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pandas=1.3.3
  - seaborn=0.11.2
  - pip=21.2.4
  - pip:
      - networkx==2.6.3
      - pennylane==0.19.1
      - amazon-braket-ocean-plugin==1.0.5
      - amazon-braket-pennylane-plugin==1.5.2
      - dwave-ocean-sdk==3.5.0
      - python-sat==0.1.7.dev15
      - nnf==0.3.0
      - ortools==8.2.8710
      - pyqubo==1.0.13
      - qiskit==0.34.1
      - qiskit-optimization==0.3.2
      - scikit-learn==1.0.2
      - pyyaml==5.4.1
      - qubovert==1.2.4
      - inquirer==2.7.0
      - more-itertools==8.12.0
